# Generated by Django 2.2.19 on 2022-06-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('moderator', 'Moderator'), ('admin', 'admin')], default='user', max_length=100),
        ),
    ]
