# Generated by Django 2.2.19 on 2022-06-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationcode',
            name='code',
            field=models.IntegerField(default=1111),
        ),
    ]
